### ISSUE TITLE
User Links containing a hyphen are broken

### ISSUE THREAD

**Issue by StellaeAlis** [Infinytum/rawr#39]
In [this post](https://furry.engineer/@NeoFox/111461632223081259), only the part of the user until the hyphen is marked. Clicking it also gives an error. 

<details><summary>Screenshots</summary>
<p>

![IMG_4578](https://github.com/Infinytum/rawr/assets/80097964/99a2f6a9-287d-458c-8e77-09046f51a868)
![IMG_4579](https://github.com/Infinytum/rawr/assets/80097964/180e1c21-572b-40aa-9df9-ac3a1fce3c2f)

</p>
</details>

**Comment by nilathedragon** [comment]
This should be fixed with the latest update

**Comment by StellaeAlis** [comment]
Still happens for links containing underscores. [Example](https://tilde.zone/@nytpu/111489531965489488)

/

**Comment by nilathedragon** [comment]
Will add underscores to the allowed character list!
